# Generated by Django 3.1 on 2020-08-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0003_auto_20200817_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(default='defaults/avatars/default_user_avatar.jpg', upload_to='pets/avatars'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaults/avatars/default_user_avatar.jpg', upload_to='users/avatars/'),
        ),
    ]
