# Generated by Django 3.1 on 2020-08-17 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='defaults/products/default_product_image.png', upload_to='products/images'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_auth.product')),
            ],
        ),
    ]
