# Generated by Django 3.1 on 2020-08-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0006_auto_20200817_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='date_birth',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
