# Generated by Django 3.1 on 2020-08-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0007_auto_20200831_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='nickname',
        ),
    ]
