# Generated by Django 3.1 on 2020-08-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0008_remove_pet_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(default='defaults/avatars/default_pet_avatar.jpg', upload_to='pets/avatars'),
        ),
    ]
