# Generated by Django 3.1 on 2020-08-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0009_auto_20200831_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(default='defaults/avatars/default_pet_avatar.png', upload_to='pets/avatars/'),
        ),
    ]
