# Generated by Django 3.1 on 2020-09-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0010_auto_20200831_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
